apiVersion: v1
kind: Service
metadata:
  name: {{ include "bte-trapi-chart.fullname" . }}
  labels:
    {{- include "bte-trapi-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "bte-trapi-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
