replicaCount: 1

image:
  repository: ahueb1/bte-trapi
  pullPolicy: IfNotPresent
  tag: latest

env:
  - name: SENTRY_ENABLED
    value: "false"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000
  nodePort: 31300

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: "12"
    memory: "24Gi"
  requests:
    cpu: "12"
    memory: "24Gi"

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
